// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabaseClient.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) {
    return { ok: false, error: "No autenticado" };
  }
  const sb = supabaseForUser(ctx);
  const { data, error } = await sb.rpc("is_admin", { _user_id: ctx.getUserId() });
  if (error) return { ok: false, error: `Error verificando permisos: ${error.message}` };
  if (data !== true) return { ok: false, error: "Acceso denegado: se requiere rol admin" };
  return { ok: true, sb };
}
function textError(msg) {
  return { content: [{ type: "text", text: msg }], isError: true };
}
function textJson(obj) {
  return {
    content: [{ type: "text", text: JSON.stringify(obj, null, 2) }],
    structuredContent: { data: obj }
  };
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "Listar productos",
  description: "Lista productos del men\xFA de Catarsis. Permite filtrar por categor\xEDa y estado activo.",
  inputSchema: {
    categoria: z.string().optional().describe("Filtro por categor\xEDa (bebidas, hamburguesas, etc.)"),
    activo: z.boolean().optional().describe("true = solo activos, false = solo inactivos, omitir = todos"),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de resultados (default 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ categoria, activo, limit }, ctx) => {
    const check = await requireAdmin(ctx);
    if (!check.ok) return textError(check.error);
    let q = check.sb.from("products").select("id, nombre, slug, categoria, precio_usd, activo, destacado, orden, descripcion_corta").order("categoria").order("orden").limit(limit ?? 100);
    if (categoria) q = q.eq("categoria", categoria);
    if (typeof activo === "boolean") q = q.eq("activo", activo);
    const { data, error } = await q;
    if (error) return textError(error.message);
    return textJson(data);
  }
});

// src/lib/mcp/tools/update-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var update_product_default = defineTool2({
  name: "update_product",
  title: "Actualizar producto",
  description: "Modifica un producto de Catarsis (precio, nombre, descripci\xF3n, activo, destacado, orden).",
  inputSchema: {
    id: z2.string().uuid().describe("UUID del producto a modificar"),
    nombre: z2.string().min(1).optional(),
    descripcion_corta: z2.string().optional(),
    precio_usd: z2.number().nonnegative().optional().describe("Precio en USD"),
    activo: z2.boolean().optional(),
    destacado: z2.boolean().optional(),
    orden: z2.number().int().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const check = await requireAdmin(ctx);
    if (!check.ok) return textError(check.error);
    const { id, ...patch } = input;
    const clean = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(clean).length === 0) return textError("No se especific\xF3 ning\xFAn campo a modificar");
    const { data, error } = await check.sb.from("products").update(clean).eq("id", id).select().single();
    if (error) return textError(error.message);
    return textJson(data);
  }
});

// src/lib/mcp/tools/get-sales-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_sales_summary_default = defineTool3({
  name: "get_sales_summary",
  title: "Resumen de ventas",
  description: "M\xE9tricas de ventas de Catarsis en un rango de fechas: ventas por categor\xEDa, top productos y por fuente (men\xFA/local/etc.).",
  inputSchema: {
    days: z3.number().int().min(1).max(365).optional().describe("\xDAltimos N d\xEDas (default 30). Alternativa a date_from/date_to."),
    date_from: z3.string().datetime().optional().describe("ISO 8601 inicio"),
    date_to: z3.string().datetime().optional().describe("ISO 8601 fin")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, date_from, date_to }, ctx) => {
    const check = await requireAdmin(ctx);
    if (!check.ok) return textError(check.error);
    const to = date_to ?? (/* @__PURE__ */ new Date()).toISOString();
    const from = date_from ?? new Date(Date.now() - (days ?? 30) * 864e5).toISOString();
    const [cat, prod, src] = await Promise.all([
      check.sb.rpc("get_sales_by_category", { date_from: from, date_to: to }),
      check.sb.rpc("get_product_sales_history", { date_from: from, date_to: to, category_filter: null }),
      check.sb.rpc("get_sales_by_source", { date_from: from, date_to: to })
    ]);
    if (cat.error) return textError(cat.error.message);
    if (prod.error) return textError(prod.error.message);
    if (src.error) return textError(src.error.message);
    return textJson({
      period: { from, to },
      by_category: cat.data,
      top_products: (prod.data ?? []).slice(0, 20),
      by_source: src.data
    });
  }
});

// src/lib/mcp/tools/get-visits-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var get_visits_summary_default = defineTool4({
  name: "get_visits_summary",
  title: "Resumen de visitas",
  description: "M\xE9tricas de tr\xE1fico web de Catarsis: total de visitas, visitantes \xFAnicos, p\xE1ginas m\xE1s populares, pa\xEDses y fuentes de tr\xE1fico.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).optional().describe("\xDAltimos N d\xEDas (default 30)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    const check = await requireAdmin(ctx);
    if (!check.ok) return textError(check.error);
    const to = (/* @__PURE__ */ new Date()).toISOString();
    const from = new Date(Date.now() - (days ?? 30) * 864e5).toISOString();
    const [totals, pages, countries, sources] = await Promise.all([
      check.sb.rpc("get_page_views_totals", { p_start: from, p_end: to }),
      check.sb.rpc("get_popular_pages", { p_start: from, p_end: to, p_limit: 10 }),
      check.sb.rpc("get_visits_by_country", { p_start: from, p_end: to }),
      check.sb.rpc("get_visits_by_source", { p_start: from, p_end: to })
    ]);
    for (const r of [totals, pages, countries, sources]) {
      if (r.error) return textError(r.error.message);
    }
    return textJson({
      period: { from, to },
      totals: totals.data?.[0] ?? totals.data,
      popular_pages: pages.data,
      by_country: countries.data,
      by_source: sources.data
    });
  }
});

// src/lib/mcp/tools/list-recent-orders.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var list_recent_orders_default = defineTool5({
  name: "list_recent_orders",
  title: "\xD3rdenes recientes",
  description: "Lista las \xF3rdenes m\xE1s recientes de Catarsis con estado, cliente, total y m\xE9todo de pago.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("Cantidad de \xF3rdenes (default 20)"),
    status: z5.enum(["NEW", "CONFIRMED", "PREPARING", "READY", "DELIVERED", "CANCELED"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    const check = await requireAdmin(ctx);
    if (!check.ok) return textError(check.error);
    let q = check.sb.from("orders").select("id, order_number, created_at, status, first_name, last_name, phone, payment_method, payment_currency, total, delivery_type").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return textError(error.message);
    return textJson(data);
  }
});

// src/lib/mcp/tools/update-config.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^4.4.3";
var update_config_default = defineTool6({
  name: "update_config",
  title: "Actualizar configuraci\xF3n",
  description: "Lee (sin value) o actualiza (con value) una clave de configuraci\xF3n global de Catarsis (ej: tasa_ves, whatsapp, instagram_url).",
  inputSchema: {
    key: z6.string().min(1).describe("Clave de configuraci\xF3n"),
    value: z6.string().optional().describe("Nuevo valor. Omitir para solo leer.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ key, value }, ctx) => {
    const check = await requireAdmin(ctx);
    if (!check.ok) return textError(check.error);
    if (value === void 0) {
      const { data: data2, error: error2 } = await check.sb.from("config").select("key, value").eq("key", key).maybeSingle();
      if (error2) return textError(error2.message);
      return textJson(data2 ?? { key, value: null });
    }
    const { data, error } = await check.sb.from("config").upsert({ key, value }, { onConflict: "key" }).select().single();
    if (error) return textError(error.message);
    return textJson(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "qucqigemdbyclxqjzkbs";
var mcp_default = defineMcp({
  name: "catarsis-mcp",
  title: "Catarsis MCP",
  version: "0.1.0",
  instructions: "Herramientas de administraci\xF3n para Catarsis Drinks & Food. Permite consultar m\xE9tricas de ventas y visitantes, listar y modificar productos del men\xFA, revisar \xF3rdenes recientes y ajustar la configuraci\xF3n global. Todas las herramientas requieren un usuario con rol admin.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, update_product_default, get_sales_summary_default, get_visits_summary_default, list_recent_orders_default, update_config_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
